# Generated by Django 6.0.4 on 2026-04-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_for', models.DateField(db_index=True, unique=True)),
                ('title_am', models.TextField()),
                ('title_en', models.TextField(blank=True, null=True)),
                ('content_am', models.TextField()),
                ('content_en', models.TextField(blank=True, null=True)),
                ('verse', models.CharField(blank=True, max_length=255, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_for'],
            },
        ),
    ]
